baseURL = "https://LukeAndrews.github.io/"
languageCode = "en-us"
title = "Luke Andrews' Apple Blog"
theme = "PaperMod"

# Enable this for sidebar/search/social/etc.
[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  defaultTheme = "dark"

